2024-07-17 10:49:19,723 INFO    StreamThr :23912 [internal.py:wandb_internal():85] W&B internal server running at pid: 23912, started at: 2024-07-17 10:49:19.722760
2024-07-17 10:49:19,724 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: status
2024-07-17 10:49:19,725 INFO    WriterThread:23912 [datastore.py:open_for_write():87] open: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\run-kdllg3nd.wandb
2024-07-17 10:49:19,728 DEBUG   SenderThread:23912 [sender.py:send():379] send: header
2024-07-17 10:49:19,728 DEBUG   SenderThread:23912 [sender.py:send():379] send: run
2024-07-17 10:49:20,035 INFO    SenderThread:23912 [dir_watcher.py:__init__():211] watching files in: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files
2024-07-17 10:49:20,035 INFO    SenderThread:23912 [sender.py:_start_run_threads():1188] run started: kdllg3nd with start time 1721227759.72376
2024-07-17 10:49:20,046 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: check_version
2024-07-17 10:49:20,046 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: check_version
2024-07-17 10:49:20,075 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: run_start
2024-07-17 10:49:20,096 DEBUG   HandlerThread:23912 [system_info.py:__init__():26] System info init
2024-07-17 10:49:20,096 DEBUG   HandlerThread:23912 [system_info.py:__init__():41] System info init done
2024-07-17 10:49:20,096 INFO    HandlerThread:23912 [system_monitor.py:start():194] Starting system monitor
2024-07-17 10:49:20,096 INFO    SystemMonitor:23912 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-07-17 10:49:20,096 INFO    HandlerThread:23912 [system_monitor.py:probe():214] Collecting system info
2024-07-17 10:49:20,101 INFO    SystemMonitor:23912 [interfaces.py:start():188] Started cpu monitoring
2024-07-17 10:49:20,101 INFO    SystemMonitor:23912 [interfaces.py:start():188] Started disk monitoring
2024-07-17 10:49:20,102 INFO    SystemMonitor:23912 [interfaces.py:start():188] Started gpu monitoring
2024-07-17 10:49:20,109 INFO    SystemMonitor:23912 [interfaces.py:start():188] Started memory monitoring
2024-07-17 10:49:20,114 INFO    SystemMonitor:23912 [interfaces.py:start():188] Started network monitoring
2024-07-17 10:49:20,117 DEBUG   HandlerThread:23912 [system_info.py:probe():152] Probing system
2024-07-17 10:49:20,119 DEBUG   HandlerThread:23912 [gitlib.py:_init_repo():56] git repository is invalid
2024-07-17 10:49:20,119 DEBUG   HandlerThread:23912 [system_info.py:probe():200] Probing system done
2024-07-17 10:49:20,119 DEBUG   HandlerThread:23912 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.19044-SP0', 'python': '3.11.9', 'heartbeatAt': '2024-07-17T14:49:20.118881', 'startedAt': '2024-07-17T14:49:19.715691', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'd:\\Works\\SomeCodes\\testing-wandb\\test-wandb.py', 'codePathLocal': 'test-wandb.py', 'codePath': 'test-wandb.py', 'host': 'PD-505W7Y3', 'username': '4475358', 'executable': 'C:\\ProgramData\\miniconda3\\envs\\wandbtestp11\\python.exe', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 2100.0, 'min': 0.0, 'max': 2100.0}, 'cpu_freq_per_core': [{'current': 2100.0, 'min': 0.0, 'max': 2100.0}], 'disk': {'/': {'total': 3726.0058555603027, 'used': 565.4867401123047}}, 'gpu': 'NVIDIA RTX A4500', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA RTX A4500', 'memory_total': 21464350720}], 'memory': {'total': 127.69602584838867}}
2024-07-17 10:49:20,119 INFO    HandlerThread:23912 [system_monitor.py:probe():224] Finished collecting system info
2024-07-17 10:49:20,119 INFO    HandlerThread:23912 [system_monitor.py:probe():227] Publishing system info
2024-07-17 10:49:20,119 DEBUG   HandlerThread:23912 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-07-17 10:49:21,051 INFO    Thread-16 :23912 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\conda-environment.yaml
2024-07-17 10:49:21,319 DEBUG   HandlerThread:23912 [system_info.py:_save_conda():224] Saving conda packages done
2024-07-17 10:49:21,320 INFO    HandlerThread:23912 [system_monitor.py:probe():229] Finished publishing system info
2024-07-17 10:49:21,324 DEBUG   SenderThread:23912 [sender.py:send():379] send: files
2024-07-17 10:49:21,324 INFO    SenderThread:23912 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-07-17 10:49:21,376 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: python_packages
2024-07-17 10:49:21,376 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: python_packages
2024-07-17 10:49:21,377 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: stop_status
2024-07-17 10:49:21,377 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-17 10:49:21,377 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: stop_status
2024-07-17 10:49:21,380 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: partial_history
2024-07-17 10:49:21,380 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: server_info
2024-07-17 10:49:21,525 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:21,525 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:49:21,525 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:21,558 DEBUG   SenderThread:23912 [sender.py:send():379] send: telemetry
2024-07-17 10:49:21,558 DEBUG   SenderThread:23912 [sender.py:send():379] send: history
2024-07-17 10:49:21,558 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: summary_record
2024-07-17 10:49:21,560 INFO    SenderThread:23912 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-17 10:49:21,560 DEBUG   SenderThread:23912 [sender.py:send():379] send: telemetry
2024-07-17 10:49:21,560 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: server_info
2024-07-17 10:49:21,637 DEBUG   SenderThread:23912 [sender.py:send():379] send: exit
2024-07-17 10:49:21,637 INFO    SenderThread:23912 [sender.py:send_exit():586] handling exit code: 0
2024-07-17 10:49:21,637 INFO    SenderThread:23912 [sender.py:send_exit():588] handling runtime: 1
2024-07-17 10:49:21,643 INFO    SenderThread:23912 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-17 10:49:21,643 INFO    SenderThread:23912 [sender.py:send_exit():594] send defer
2024-07-17 10:49:21,643 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,643 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 0
2024-07-17 10:49:21,644 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,644 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 0
2024-07-17 10:49:21,644 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 1
2024-07-17 10:49:21,644 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,644 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 1
2024-07-17 10:49:21,644 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,644 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 1
2024-07-17 10:49:21,644 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 2
2024-07-17 10:49:21,644 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,644 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 2
2024-07-17 10:49:21,644 INFO    HandlerThread:23912 [system_monitor.py:finish():203] Stopping system monitor
2024-07-17 10:49:21,658 DEBUG   SystemMonitor:23912 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-07-17 10:49:21,658 INFO    HandlerThread:23912 [interfaces.py:finish():200] Joined cpu monitor
2024-07-17 10:49:21,658 DEBUG   SystemMonitor:23912 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-07-17 10:49:21,659 INFO    HandlerThread:23912 [interfaces.py:finish():200] Joined disk monitor
2024-07-17 10:49:21,659 DEBUG   SystemMonitor:23912 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-07-17 10:49:21,726 INFO    HandlerThread:23912 [interfaces.py:finish():200] Joined gpu monitor
2024-07-17 10:49:21,727 INFO    HandlerThread:23912 [interfaces.py:finish():200] Joined memory monitor
2024-07-17 10:49:21,727 INFO    HandlerThread:23912 [interfaces.py:finish():200] Joined network monitor
2024-07-17 10:49:21,727 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,727 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 2
2024-07-17 10:49:21,727 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 3
2024-07-17 10:49:21,727 DEBUG   SenderThread:23912 [sender.py:send():379] send: stats
2024-07-17 10:49:21,727 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,727 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 3
2024-07-17 10:49:21,727 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,728 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 3
2024-07-17 10:49:21,728 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 4
2024-07-17 10:49:21,728 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,728 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 4
2024-07-17 10:49:21,728 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,728 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 4
2024-07-17 10:49:21,728 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 5
2024-07-17 10:49:21,728 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,728 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 5
2024-07-17 10:49:21,728 DEBUG   SenderThread:23912 [sender.py:send():379] send: summary
2024-07-17 10:49:21,732 INFO    SenderThread:23912 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-17 10:49:21,733 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,733 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 5
2024-07-17 10:49:21,733 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 6
2024-07-17 10:49:21,733 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,733 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 6
2024-07-17 10:49:21,733 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,733 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 6
2024-07-17 10:49:21,734 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: status_report
2024-07-17 10:49:21,830 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 7
2024-07-17 10:49:21,831 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,831 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 7
2024-07-17 10:49:21,831 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,831 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 7
2024-07-17 10:49:21,831 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 8
2024-07-17 10:49:21,831 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,831 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 8
2024-07-17 10:49:21,831 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,832 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 8
2024-07-17 10:49:21,832 INFO    SenderThread:23912 [job_builder.py:build():440] Attempting to build job artifact
2024-07-17 10:49:21,832 INFO    SenderThread:23912 [job_builder.py:_get_source_type():580] no source found
2024-07-17 10:49:21,833 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 9
2024-07-17 10:49:21,833 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:21,833 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 9
2024-07-17 10:49:21,833 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:21,833 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 9
2024-07-17 10:49:21,833 INFO    SenderThread:23912 [dir_watcher.py:finish():358] shutting down directory watcher
2024-07-17 10:49:22,064 INFO    SenderThread:23912 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\config.yaml
2024-07-17 10:49:22,064 INFO    SenderThread:23912 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\conda-environment.yaml
2024-07-17 10:49:22,064 INFO    SenderThread:23912 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\wandb-metadata.json
2024-07-17 10:49:22,064 INFO    SenderThread:23912 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\wandb-summary.json
2024-07-17 10:49:22,065 INFO    SenderThread:23912 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\requirements.txt
2024-07-17 10:49:22,065 INFO    SenderThread:23912 [dir_watcher.py:finish():388] scan: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files
2024-07-17 10:49:22,066 INFO    SenderThread:23912 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\conda-environment.yaml conda-environment.yaml
2024-07-17 10:49:22,066 INFO    SenderThread:23912 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\config.yaml config.yaml
2024-07-17 10:49:22,066 INFO    SenderThread:23912 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\requirements.txt requirements.txt
2024-07-17 10:49:22,068 INFO    SenderThread:23912 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\wandb-metadata.json wandb-metadata.json
2024-07-17 10:49:22,068 INFO    SenderThread:23912 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\files\wandb-summary.json wandb-summary.json
2024-07-17 10:49:22,071 INFO    SenderThread:23912 [sender.py:transition_state():614] send defer: 10
2024-07-17 10:49:22,071 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:49:22,071 INFO    HandlerThread:23912 [handler.py:handle_request_defer():184] handle defer: 10
2024-07-17 10:49:22,072 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: defer
2024-07-17 10:49:22,072 INFO    SenderThread:23912 [sender.py:send_request_defer():610] handle sender defer: 10
2024-07-17 10:49:22,072 INFO    SenderThread:23912 [file_pusher.py:finish():169] shutting down file pusher
2024-07-17 10:49:22,225 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:22,225 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:49:22,225 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:22,233 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:22,233 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:49:22,233 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:22,235 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:22,235 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '121'}
2024-07-17 10:49:22,235 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:22,270 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:22,270 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:49:22,270 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:22,645 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:22,645 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:22,753 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:22,753 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:49:22,753 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:23,355 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:23,355 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '121'}
2024-07-17 10:49:23,355 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:23,355 INFO    wandb-upload_4:23912 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2911, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\wandbtestp11\Lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-07-17 10:49:23,473 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:23,473 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:49:23,473 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:23,504 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:23,504 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:49:23,504 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:23,529 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:23,529 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:49:23,529 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:23,657 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:23,657 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:24,671 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:24,671 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:24,933 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:24,934 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:49:24,934 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:25,529 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:25,529 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '121'}
2024-07-17 10:49:25,530 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:25,675 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:25,675 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:25,734 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:25,735 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:49:25,735 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:25,909 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:25,909 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:49:25,909 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:26,078 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:26,078 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:49:26,078 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:26,688 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:26,688 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:27,691 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:27,691 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:28,693 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:28,694 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:29,699 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:29,699 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:29,846 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:29,846 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:49:29,846 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:29,973 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:29,973 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:49:29,973 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:30,181 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:30,181 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '121'}
2024-07-17 10:49:30,181 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:30,562 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:30,562 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:49:30,562 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:30,706 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: status_report
2024-07-17 10:49:30,706 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:30,707 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:31,018 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:31,018 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:49:31,019 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:31,711 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:31,711 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:32,717 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:32,718 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:33,723 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:33,723 DEBUG   SenderThread:23912 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:35,725 DEBUG   HandlerThread:23912 [handler.py:handle_request():158] handle_request: status_report
2024-07-17 10:49:36,738 WARNING StreamThr :23912 [internal.py:is_dead():413] Internal process exiting, parent pid 23228 disappeared
2024-07-17 10:49:36,738 ERROR   StreamThr :23912 [internal.py:wandb_internal():151] Internal process shutdown.
2024-07-17 10:49:37,736 INFO    SenderThread:23912 [sender.py:finish():1608] shutting down sender
2024-07-17 10:49:37,736 INFO    SenderThread:23912 [file_pusher.py:finish():169] shutting down file pusher
2024-07-17 10:49:37,736 INFO    WriterThread:23912 [datastore.py:close():296] close: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104919-kdllg3nd\run-kdllg3nd.wandb
2024-07-17 10:49:37,736 INFO    HandlerThread:23912 [handler.py:finish():882] shutting down handler
2024-07-17 10:49:37,736 INFO    SenderThread:23912 [file_pusher.py:join():175] waiting for file pusher
2024-07-17 10:49:38,624 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:38,624 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:49:38,624 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:39,145 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:39,145 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:49:39,145 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:39,296 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:39,296 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:49:39,296 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:39,596 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:39,596 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '121'}
2024-07-17 10:49:39,596 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:40,445 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:40,445 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:49:40,445 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:56,147 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:56,147 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '121'}
2024-07-17 10:49:56,147 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:57,005 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:57,005 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:49:57,005 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:57,400 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:57,400 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:49:57,400 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:58,341 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:58,341 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:49:58,341 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:58,559 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:58,559 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:49:58,559 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:50:31,907 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:50:31,907 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '121'}
2024-07-17 10:50:31,907 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:50:32,667 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:50:32,667 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:50:32,667 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:50:33,006 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:50:33,006 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:50:33,006 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:50:35,747 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:50:35,747 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:50:35,747 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:50:37,499 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:50:37,499 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:50:37,499 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:51:37,584 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/requirements.txt?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L1sZt8vHFhrO6IGMWMmk5qgDHf8%2FwGiCuYn57Pzi489Y48fcoKyUEm2DNtWy6w%2BplQA2%2B%2F%2FkuS6Z4WlYf94ir3m5uYB9dqNUhNAo1S%2F2R7LSQ%2Fgo3oLUQ4wqgg2j0vqM5LrLs%2BcZxN93dM7N3luHAOpMOFwyo%2FoQ%2F%2BS7r4B12oqkJERkCBBVyvma6C4ZEflufgK4IqyB4k0IvfNX0KZ8iFN2%2BrqiH8jYgN%2FWM5%2B%2FMuoNwt31lIYMDVNLhLyX44ouu59AXmNcsPPZmPIEpjJIt%2F%2BeBIUsW39MYjKpHE54mKHpMHBr10EDfyKe0X4ubnki3A0R0LsTJOgtB99ylYTucw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:51:37,584 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:51:37,585 ERROR   wandb-upload_3:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:51:38,883 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-summary.json?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TvH9Wb8T4TkbQ4MltFYIPWKWAe1RUISVNMKTJY%2FK36neuEszUzAMJWfxh4fN476fuvPKnAEx4B37UNty6NIKIZCa6AkEr%2B%2Bkjme5W%2BLFtv6u08GDqOyTT8FkPizFdsHuYtBjY7jHGYTdHox6KojLwk%2BcyuVYQ8ebR4JwrIdHd27bYNPrQf%2F4Mgsf9VEfCw5RaxHEZ6cee4v7kgsPAtJVmCFgT1DgCpZuZ6FkP%2B3wUAG8BydVOeDOhy1yejL7iWCL8ldaIAOTxnXZK2j%2B5Jg%2BNAZe778Au1cqw1bY6DHCDih8REH3SuHzORea2iiN%2FHfJeXBk8pHCm6A8rPoI3OLouw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:51:38,883 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '121'}
2024-07-17 10:51:38,883 ERROR   wandb-upload_4:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:51:40,690 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/wandb-metadata.json?Expires=1721314161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=twuBHL4d1EaxxcPqQEoOUZy99flgyXkRDpmZc3ttSRmPDVb2tcET6Jj18i0R6HolMOC99zmsWEI7taxgvVIYHpWMfbk0HLVfSfVceET%2BY%2Ft2SlFh2MfNJRN20a6vUZ39cefvvlR7LAfutYjFlV2VsSwpTOX2Jbu3QfQmBanKwD0EpE12K45W4z51m7E3iDvrmlHK4CXKdvhdI5p3fhDgZRpsOrY8SlmkJkst65GiHyobGbPo%2BxzcD1EJk%2F3Z5n%2FpI70niLh5xL3N09wp%2F3Oct%2BwLp0Yv13wwSkGb2gJCZPw9vNXJKiEKf8UW%2BhHesffK1UFfDeygB9b4iSQA0PLYgw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:51:40,690 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:51:40,690 ERROR   wandb-upload_0:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:51:43,222 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/conda-environment.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hXVcCJtdRW0WvELmAZB1zhd7R78v2ms%2FOaEuFmLg5tkUxmRnxMr0MDOIvbdsbckBTFWNJorx6zTRXsP1advfblHuorpQfOpUu5le0JJMkjnRD8IkzdjI1ZK6vUGEiuFk8yEME9alm7zt4yIO1hx%2BgYlyacfgImppnHAfYeNE%2BN8mXfgZlVWtnQM0H52bsksof2%2BCCWdtiSDDX0n59SbdViHfNIrluJrhnhLzugWVkiFx4J7f%2BPC4lzbTzPkgkw3FPu9se84XAzh4p02uicKepHMVuv90WFhZIQoSKBAGxyjog%2FjIfdhc%2BhqzvSwfUBaudBmyjjTY6R4wzGf%2Fnfdhsg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:51:43,222 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:51:43,222 ERROR   wandb-upload_1:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:51:48,073 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/kdllg3nd/config.yaml?Expires=1721314162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=moW7rUVAcrhE7vij7M6sgJctA2AkfPgR2oYh9aihX1vvoJLzLaOfjr6qxNWE%2F0x0EAJkseeMucEuLQZQtDQF%2BvBstomXqIVbzhBdhx0R6HZdqooG1TvJRPEF9z24SloQpv8gx8XLS9bFLkM98FZTK9%2BYHj%2FV2fhb1AF0uKtCCvpta%2FMj6%2BiUYZ7I5uoKOdVJbEch8czGv821RDRk%2F4FWQK8%2B%2F88ZUz09aERR2Ph8nLWh7CRc89%2FBgXPiT%2B%2F2ZCtNlG8lXAlVNAEQqV2M5iF62UdO0nfmZfwkdiD7lkLJQvllfaPISgVjbzGGOlsvre1Tlz8H9O7BPdmW945KSZcOQg%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:51:48,073 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:51:48,073 ERROR   wandb-upload_2:23912 [internal_api.py:upload_file():2891] upload_file response body: ''
